# docker build -f Dockerfile_tomcat8 --tag gwess/tomcat:8.5 .
# docker run -d --name tomcat1 -e JAVA_OPTS="-DjvmRoute=jvm1" --hostname=tomcat1 gwess/tomcat:8.5

# java of openjdk
# Using oracle-jdk
# FROM openweb/oracle-tomcat:8.5-jre8
FROM tomcat:8.5
MAINTAINER YoungJin Lee <lyjguy@gridwiz.com>

RUN apt-get update -y && apt-get install -y vim locales locales-all

#ENV JAVA_OPTS="${JAVA_OPTS} -DjvmRoute=${JVM_ROUTER}"
#ENV JAVA_OPTS="${JAVA_OPTS} -Dhostname=${HOSTNAME}"
ENV TOMCAT_HOME /usr/local/tomcat
ENV LC_ALL en_US.UTF-8
ENV LANG en_US.UTF-8
ENV LANGUAGE en_US.UTF-8
# RUN locale-gen ko_KR.UTF-8
# ENV LC_ALL ko_KR.UTF-8

RUN mkdir -p /usr/local/tomcat/webapps mkdir -p ${TOMCAT_HOME}/secure

# timezone(if none zonifo install tzdata)
ENV TZ=Asia/Seoul
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

COPY server.xml ${TOMCAT_HOME}/conf/
COPY emskeystore.jks ${TOMCAT_HOME}/secure/
COPY index.jsp ${TOMCAT_HOME}/webapps/ROOT/
COPY web.xml ${TOMCAT_HOME}/webapps/ROOT/WEB-INF/
