# docker build --rm -f Dockerfile_hadoop --tag gwess/centos7_hadoop .
# docker run -d -v /sys/fs/cgroup:/sys/fs/cgroup:ro --cap-add SYS_ADMIN -p 50070:50070 -p 50075:50075 -p 2122:2122 --name hadoop gwess/centos7_hadoop

FROM gwess/centos7
MAINTAINER YoungJin Lee <lyjguy@gridwiz.com>

USER root

RUN yum clean all && yum update -y && yum install -y httpd vim wget sudo locales locales-all
RUN systemctl enable httpd.service

ENV LC_ALL en_US.UTF-8
ENV LANG en_US.UTF-8
ENV LANGUAGE en_US.UTF-8

# timezone(if none zonifo install tzdata)
ENV TZ=Asia/Seoul
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

# openjdk install
RUN yum install -y java-1.8.0-openjdk-devel.x86_64
ENV JAVA_HOME=/usr/lib/jvm/java-1.8.0-openjdk-1.8.0.191.b12-1.el7_6.x86_64
ENV PATH $PATH:$JAVA_HOME/bin

# hadoop info
ENV HADOOP_VERSION 2.9.2
ENV HADOOP_URL http://mirror.navercorp.com/apache/hadoop/common/hadoop-2.9.2/hadoop-$HADOOP_VERSION.tar.gz

# hadoop required software
RUN yum install -y rsync openssh-server openssh-clients openssh-askpass passwd
RUN yum update -y libselinux
RUN mkdir /var/run/sshd

# passwordless ssh
RUN ssh-keygen -q -N "" -t dsa -f /etc/ssh/ssh_host_dsa_key
RUN ssh-keygen -q -N "" -t rsa -f /etc/ssh/ssh_host_rsa_key
RUN ssh-keygen -q -N "" -t ecdsa -f /etc/ssh/ssh_host_ecdsa_key
RUN ssh-keygen -q -N "" -t rsa -f /root/.ssh/id_rsa
RUN cp /root/.ssh/id_rsa.pub /root/.ssh/authorized_keys

# hadoop install
RUN curl -s $HADOOP_URL \
 | tar -zx -C /usr/local/
RUN cd /usr/local && ln -s ./hadoop-2.9.2 hadoop

ENV HADOOP_PREFIX /usr/local/hadoop

RUN sed -i '/^export JAVA_HOME/ s:.*:export JAVA_HOME=/usr/lib/jvm/java-1.8.0-openjdk-1.8.0.191.b12-1.el7_6.x86_64:' $HADOOP_PREFIX/etc/hadoop/hadoop-env.sh

# single node
RUN mkdir $HADOOP_PREFIX/input
RUN cp $HADOOP_PREFIX/etc/hadoop/*.xml $HADOOP_PREFIX/input

# pseudo distributed
COPY core-site.xml $HADOOP_PREFIX/etc/hadoop/core-site.xml
COPY hdfs-site.xml $HADOOP_PREFIX/etc/hadoop/hdfs-site.xml

COPY ssh_config /root/.ssh/config
RUN chmod 600 /root/.ssh/config
RUN chown root:root /root/.ssh/config

COPY bootstrap.sh /etc/bootstrap.sh
RUN chown root:root /etc/bootstrap.sh
RUN chmod 700 /etc/bootstrap.sh

# fix the 254 error code
RUN sed -i "/^[^#]*UsePAM/ s/.*/#&/" /etc/ssh/sshd_config
RUN echo "UsePAM no" >> /etc/ssh/sshd_config
RUN echo "Port 2122" >> /etc/ssh/sshd_config

EXPOSE 80
# Hdfs ports
EXPOSE 50010 50020 50070 50075 50090
# Mapred ports
EXPOSE 19888
#Yarn ports
EXPOSE 8030 8031 8032 8033 8040 8042 8088
#Other ports
EXPOSE 49707 2122

CMD ["/usr/sbin/sshd", "-D"]
