FROM gwess/centos7_hadoop
MAINTAINER YoungJin Lee <lyjguy@gridwiz.com>

# datanode port
EXPOSE 50010 50020 50075
#Yarn nodemanager ports
EXPOSE 8040 8042 8044 8048 8049
#Other ports
EXPOSE 49707 2122 9000

CMD ["sh","-c", "/usr/sbin/sshd -D"]
