FROM gwess/centos7_hadoop
MAINTAINER YoungJin Lee <lyjguy@gridwiz.com>

# namenode ports
EXPOSE 50070
# secondary namenode ports
#EXPOSE 50090
# datanode port
#EXPOSE 50010 50020 50075
# Mapred jobhistory ports
EXPOSE 10020 19888 19890
#Yarn resourcemanager ports
EXPOSE 8030 8031 8032 8033 8088
#Yarn nodemanager ports
EXPOSE 8040 8042 8044 8048 8049
#Yarn timeline service ports
EXPOSE 10020 8188 8190
#Yarn router ports
EXPOSE 8089
#Other ports
EXPOSE 49707 2122 9000

CMD ["sh","-c", "/usr/sbin/sshd -D"]
