influxdb:
  restart: unless-stopped
  image: influxdb:1.4.2
  ports:
   - "8086:8086"
  volumes:
   - /var/data/influxdb/influxdb.conf:/etc/influxdb/influxdb.conf:ro
   - /var/data/influxdb/data:/var/lib/influxdb
  container_name: influxdb
  command: -config /etc/influxdb/influxdb.conf
